sudo: required
dist: trusty
language: generic

compiler:
  - gcc

notifications:
  email:
    on_failure: always
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="kinetic" PRERELEASE=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - source .ci_config/travis.sh
